version: "3"
services:
  postgres:
    image: postgres:latest
    networks:
      - postgres
    volumes:
      - /data/postgres:/data/postgres
    env_file:
      - docker.env
 
  codetain-cabs:
    image: codetain_cabs_test
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    networks:
      - postgres
 
networks:
  postgres:
    driver: bridge