export const mockUserRepository = [
  {
    id: 1,
    email: 'testmail1@gmail.com',
    password: 'testpassword1',
    name: 'testname1',
    surname: 'testsurname1',
    dateOfBirth: new Date('19:01:2000T00:00:01'),
    address: 'testaddress1',
    verified: true,
    confirmationCode: 'randomcode1',
  },
  {
    id: 2,
    email: 'testmail2@gmail.com',
    password: 'testpassword2',
    name: 'testname2',
    surname: 'testsurname2',
    dateOfBirth: new Date('19:01:2000T00:00:01'),
    address: 'testaddress2',
    verified: true,
    confirmationCode: 'randomcode2',
  },
  {
    id: 3,
    email: 'testmail3@gmail.com',
    password: 'testpassword3',
    name: 'testname3',
    surname: 'testsurname3',
    dateOfBirth: new Date('19:01:2000T00:00:01'),
    address: 'testaddress3',
    verified: false,
    confirmationCode: 'randomcode3',
  },
];
